### ISSUE TITLE
Build Failed on step 25 after docker hub image pull

### ISSUE THREAD

**Issue by Maharshi-Pathak** [ecobee/building-controls-simulator#124]
Hi @TStesco, 

I, Kunind, and Emma are trying to build the docker image on the latest updates. We are getting the same error, so opened this issue and request you to guide on how to move forward. I am attaching an image below for your reference, but just reading through the error message it seems the repo is missing `requirements.txt` file. Do you know what's wrong here?
![image](https://user-images.githubusercontent.com/64644720/104753695-57e60c00-5726-11eb-8256-4c8c9f2cdf6a.png)

**Comment by tomstesco** [comment]
Looks like they got flag by .gitignore somehow, adding now. Are you building the image though? If you use docker hub you shouldn't have to build the image. You will have to change the name in `docker-compose.yml` so it matches the image downloaded.

**Comment by Maharshi-Pathak** [comment]
That worked, Thanks for the update.
