### ISSUE TITLE
You sure this isn't supposed to be step size as the second parameter?

### ISSUE THREAD

**Issue by daviddecobee** [ecobee/building-controls-simulator#40]
https://github.com/ecobee/building-controls-simulator/blob/ffe163a3901f443eb7fc3443ea05a2b2d29a7eb3/src/python/BuildingControlsSimulator/BuildingModels/EnergyPlusBuildingModel.py#L234

**Comment by tomstesco** [comment]
yupe that was incorrect - fixed on `controller-models` branch and will merge soon with other v1.0 additions.

**Comment by tomstesco** [comment]
addressed in https://github.com/ecobee/building-controls-simulator/pull/44
