### ISSUE TITLE
Rename method?

### ISSUE THREAD

**Issue by daviddecobee** [ecobee/building-controls-simulator#41]
I find it a bit strange to call do_step twice in slightly different contexts. Maybe do_step should be called something different for the two calls?

https://github.com/ecobee/building-controls-simulator/blob/ffe163a3901f443eb7fc3443ea05a2b2d29a7eb3/src/python/BuildingControlsSimulator/Simulator/Simulation.py#L161

**Comment by tomstesco** [comment]
the paradigm I was thinking of is that the Simulation class implements the causality of the models and calls the models in order, carrying over the outputs as inputs to the next. I could specify the method as `controller_step` and `building_step`, does that sound better?

**Comment by tomstesco** [comment]
closing for now, can revisit if this is too confusing during development.
