### ISSUE TITLE
jupyter_lab.sh missing in setup DIR

### ISSUE THREAD

**Issue by Maharshi-Pathak** [ecobee/building-controls-simulator#55]
I am having issues in the next step of the process in the container build, i.e. creating the network from the docker image. I get the same non-zero code error 127 when it tried to find the jupyter_lab.sh file. ( image attached)
![image](https://user-images.githubusercontent.com/64644720/95002933-6bba9780-05a7-11eb-85fc-4c75ac167b65.png)

**Comment by tomstesco** [comment]
I have this fixed on https://github.com/ecobee/building-controls-simulator/tree/docker-compose-fix, I'll merge this to master later today.

**Comment by tomstesco** [comment]
https://github.com/ecobee/building-controls-simulator/blob/master/scripts/setup/jupyter_lab.sh is available on `master` now. Let me know if there are any other issues.

Addressed in https://github.com/ecobee/building-controls-simulator/pull/57.
