### ISSUE TITLE
Readme.md update

### ISSUE THREAD

**Issue by Maharshi-Pathak** [ecobee/building-controls-simulator#59]
under the test section; the path for copying the example IDF file has been updated to `idf/v8-9-0/xyz/abc.idf`

**Comment by tomstesco** [comment]
Thanks for flagging, I'm updating the example to use the idf file included in the repo at: 
```test/idf/v8-9-0/AZ_Phoenix_gasfurnace_crawlspace_IECC_2018_cycles.idf```

Addressed in https://github.com/ecobee/building-controls-simulator/pull/61.
