### ISSUE TITLE
epvm.sh does not read the .env's ENERGYPLUS_INSTALL_DIR="${EXT_DIR}/EnergyPlus" correctly

### ISSUE THREAD

**Issue by Maharshi-Pathak** [ecobee/building-controls-simulator#71]
After building the container when I try to set the Eplus version to 8.9.0 using the `bash scripts/epvm.sh 8-9-0`, I am getting the "directory not found" error. I am working in VS code that I opened from the container. 
![image](https://user-images.githubusercontent.com/64644720/96750397-e3efce00-1399-11eb-976d-0bcd6719c04e.png) 
Let me know if I doing something wrong?

**Comment by tomstesco** [comment]
ya ive seen some issues with how the shell expansion works across platforms. I'm going to push a fix removing the quotation marks and not using $HOME internally, that should fix this. You'll need to then pull the changes off `master` and rebuild the docker image. I'll post a link here when those changes are up.

**Comment by Maharshi-Pathak** [comment]
I worked with dr. Kane today and was able to figure out the error. We have a PR ready if you have not started working on this, maybe we can push those changes to the upstream repo as a PR for review as well?

**Comment by tomstesco** [comment]
great! if you can put those changes in a branch off of the current `dev` branch and make a PR to `dev` from the branch ill merge it, and then I'll merge them into `master` after review. 👍
