### ISSUE TITLE
Unable to install BCS

### ISSUE THREAD

**Issue by sugirdhalakshmi** [ecobee/building-controls-simulator#99]
Installed docker successfully and made changes to env and docker-compose.yml. After making the changes, failed to build the docker image with docker-compose run --service-ports building-controls-simulator bash. Error message attached. 
![Screen Shot 2020-11-16 at 1 44 02 PM](https://user-images.githubusercontent.com/62436486/99306427-71480600-2812-11eb-9d71-88b59ec92d5d.png)

**Comment by tomstesco** [comment]
looks like a weird issue with downloading and installing nodejs. Haven't seen this before, were there network issues at this time?

**Comment by sugirdhalakshmi** [comment]
No.. I dint have any network issues.

**Comment by tomstesco** [comment]
Did you try running with `docker-compose up`? I can take a look at your .env file if that doesn't work.
